[default]
     [default.services.gaji-gesa-api.paths]
            v2-create-user="/v2/users"

    [default.services]
        test-api-payments.url = "https://gorest.co.in/public"


[test]
   [test.services.gaji-gesa-api.paths]
        v2-create-user="/v2/users"
        v2-get-specific-user="/v2/users/{id}"
        gaji-gesa-profile-token="3992b1450ea2fdb2a0d41253b84f4fe9547cde91afad56d110fc44b50793ff84"


    [test.services]
        gaji-gesa-api.url = "https://gorest.co.in/public"


[isolation]
    [isolation.services.test-api-payments.paths]
       v2-create-user="/v2/users"
        v2-get-specific-user="/v2/users/{id}"
        gaji-gesa-profile-token="3992b1450ea2fdb2a0d41253b84f4fe9547cde91afad56d110fc44b50793ff84"


    [isolation.services]
        test-api-payments.url = "https://gorest.co.in/public"